//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Student
    {
        public Student()
        {
            this.AttendanceRegisters = new HashSet<AttendanceRegister>();
        }
        

        [Required]
        [DisplayName("Enrollment No.")]
        public string EnrollmentID { get; set; }

        [Required]
        [DisplayName("Student Name")]
        public string StudentName { get; set; }

        [Required]
        [DisplayName("Student Address")]
        public string StudentAddress { get; set; }

        [Required]
        [DisplayName("Select Study Centre")]
        public string SchoolID { get; set; }

        [Required]
        [DisplayName("Select Course")]
        public string CourseID { get; set; }

        [Required]
        [DisplayName("Select Section")]
        public string SectionID { get; set; }

        [DisplayName("Student Photo")]
        public string StudentPhoto { get; set; }

        [Required]
        [DisplayName("Father Name")]
        public string FatherName { get; set; }

        [DisplayName("Mother Name")]
        public string MotherName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Date of Birth")]
        public Nullable<System.DateTime> DOB { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Date of Admission")]
        public Nullable<System.DateTime> DOA { get; set; }

        [Required]
        [DisplayName("Father Mobile No.")]
        public Nullable<decimal> FatherMobNo { get; set; }

        [DisplayName("Mother Mobile No.")]
        public Nullable<decimal> MotherMobNo { get; set; }

        [DisplayName("Alternate Mobile No.")]
        public Nullable<decimal> AlterNateNo { get; set; }

        [DisplayName("Select Gender")]
        public string Gender { get; set; }
        public virtual ICollection<AttendanceRegister> AttendanceRegisters { get; set; }
        public virtual Course Course { get; set; }
        public virtual School School { get; set; }
        public virtual Section Section { get; set; }
    }
}
