//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public string TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAddress { get; set; }
        public string Qualification1 { get; set; }
        public string Qualification2 { get; set; }
        public string Qualification3 { get; set; }
        public string Qualification4 { get; set; }
        public string SubjectID { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
